### PR TITLE
:bug: Support 1.20.3

### PR DESCRIPTION
**Pull request by ChenCMD**

### CODE REVIEW

**Comment by EstEarth202** [comment]
@ChenCMD Eh? I would like to ask first to be sure, does this update have a command `return fail` as well?

**Comment by ChenCMD** [comment]
@EstEarth202 
> @ChenCMD Eh? I would like to ask first to be sure, does this update have a command `return fail` as well?

Oh, I didn't know there was such a thing. I'll add it.

**Comment by EstEarth202** [comment]
Glad to help. Because I remember from slicedlime video that it was added.

> A new subcommand `return fail` has been added to make the whole function fail (i.e. return success=0 and result=0)

But I saw it says subcommand so I'm not sure.

**Comment by misode** [comment]
Change look good in general, will make adjustments after merging

**Pull request merged**
