### PR TITLE
:bug: Fix macro indentation not being taken into account

### LINKED ISSUE #1081: Indexed macro lines give error warning
When a macro line gets indented (by any amount) it gives this error "Failed to match any children in the command syntax tree".
If the indentation is deleted the error goes away

### PR DESCRIPTION
**Pull request by ChenCMD**
Fix #1081

### CODE REVIEW

**Comment by misode** [comment]
Can you give an example command where this issue applies?

**Comment by ChenCMD** [comment]
```mcfunction
# macro command with indent
    $say $(message)
```

**Review by SPGoding — COMMENTED** [review]
Haven't touched the code for a while but I think the `test` methods are not supposed to mutate the state of the `reader`. And iirc the `skipSpace()` method will change the cursor of it. Not sure how to fix that though.

**Comment by ChenCMD** [comment]
> Haven't touched the code for a while but I think the `test` methods are not supposed to mutate the state of the `reader`. And iirc the `skipSpace()` method will change the cursor of it. Not sure how to fix that though.
> @SPGoding 


Since the StringReader is cloned and passed to SyntaxComponentParser#test, changing the cursor doesn't seem to be a problem, does it?
https://github.com/SpyglassMC/Spyglass/blob/1a18e7eeb3367d3c44157d979194658d5243fff8/src/services/common.ts#L108

**Review by SPGoding — APPROVED** [review]
Yeah you're right, sorry!

**Pull request merged**
